name: Restrict Merge to Main

on:
  pull_request:
    branches:
      - main

jobs:
  restrict-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is dev
        if: github.base_ref != 'dev'
        run: |
          echo "Error: Pull requests to 'main' must come from the 'dev' branch."
          exit 1
